# Generated by Django 3.2.7 on 2021-12-19 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20211219_1032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserEvent',
        ),
    ]
